### ISSUE TITLE
GL.CreateShader doesn't return a uint shaderID

### ISSUE THREAD

**Issue by roceal** [carmack78/OpenGLDotNet#1] opened 2018-06-30 10:15 UTC
I had a quick look through GL.CoreWrappers.cs and this problem seems to also happen for CreateProgram. Is there another way to get the shader or program's id?

**Comment by taylaninan** [comment] 2018-06-30 17:37
Hi Roceal,

You're right. There is an obviously "conversion" error done by me. Thanks for reporting this bug.
The correct code should be like that:

        // GLAPI GLuint APIENTRY glCreateShader (GLenum type)
        public static GLuint CreateShader(GLenum type)
        {
            if (glCreateShader != null)
            {
                return glCreateShader(type);
            }
        }

        // GLAPI GLuint APIENTRY glCreateProgram (void)
        public static GLuint CreateProgram()
        {
            if (glCreateProgram != null)
            {
                return glCreateProgram();
            }
        }

**Comment by taylaninan** [comment] 2018-06-30 17:54
OK, the actual "bug fixing" proved a little bit complicated than I have written in my previous post.
BUT, the bug fix has been implemented, and pushed to the GitHub.
I think you can continue to work with your code with the latest source codes.

Please, let me know if there any other bugs in the codes.

**Closed as completed by taylaninan** 2018-06-30 17:54 UTC

**Comment by sunkin351** [comment] 2019-05-18 22:22
@carmack78 Could you push an update to this library's Nugget package? The problem is still present there. (Or are you not the one who published that?)
